version: "3.7"
services:
  rabbit1:
    build:
      context: rabbit/
    hostname: rabbit1
    ports:
      - 8081:15672
      - 55671:5672
    networks:
      - rabbits
  rabbit2:
    build:
      context: rabbit/
    hostname: rabbit2
    ports:
      - 8082:15672
      - 55672:5672
    networks:
      - rabbits
  rabbit3:
    build:
      context: rabbit/
    hostname: rabbit3
    ports:
      - 8083:15672
      - 55673:5672
    networks:
      - rabbits
  rocky:
    build:
      context: rocky/
    volumes:
      - ./app:/app
    networks:
      - rabbits
networks:
  rabbits: